# Generated by Django 5.1.3 on 2024-11-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='publication_year',
        ),
    ]
