# Generated by Django 5.1.3 on 2024-11-22 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_remove_author_books_book_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
