# Generated by Django 5.1.3 on 2024-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_series_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="books", to="books.author"),
        ),
    ]
