# Generated by Django 5.1.3 on 2024-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='authors',
            field=models.ManyToManyField(related_name='series', to='books.author'),
        ),
    ]
